### PR TITLE
SPTextUtil.harSPINRDF() to allow non-SPIN properties on Commands

### LINKED ISSUE #2: SPTextUtil.hasSPINRDF() prohibits Commands with non-SPIN properties
This [condition](../blob/master/src/main/java/org/spinrdf/util/SPTextUtil.java#L181)

    if(!RDF.type.equals(o.getPredicate()) && !SP.text.equals(o.getPredicate()) && !SPIN.thisUnbound.equals(o.getPredicate()))

checks whether a command has SPIN RDF attached, but also prevents commands from having additional properties.

I think a proper solution would be to move this code from the util class into a `Command.hasSPINRDF()` method, which would be implemented differently by subclasses such as `Ask`, `Construct` etc. They could check the existence of "root" properties such as `sp:where` based on the [SPIN SPARQL Syntax](http://spinrdf.org/sp.html).

If we agree, I will try to make a PR.

### PR DESCRIPTION
**Pull request by pumba-lt**
Fixes #2 
This method should probably move to `Command.hasSPINRDF()` eventually

### CODE REVIEW

**Comment by afs** [comment]
https://github.com/blog/1506-closing-issues-via-pull-requests

@pumba-lt  Can we try to the GH automation? Please add "resolves #2" as a commit message and (I think!) it will close the issue when this is merged. (It can be an empty commit - it is just the message that matters.)

**Comment by pumba-lt** [comment]
Uhm, but I commit to my fork/branch where there is no such issue?
I had added "Fixes #2" to the pull request message here -- isn't that the same?

**Comment by afs** [comment]
Reading the GH documentation (see link above) I think what you have done will work.  We'll find out!

**Comment by pumba-lt** [comment]
And who decides whether to merge the PRs?

**Comment by afs** [comment]
See issue #6. The suggestion is when enough "+1" are given.

**Comment by pumba-lt** [comment]
So, how long before anyone gives +1? I don't know if I should contribute more if the changes will take forever to merge...

**Comment by afs** [comment]
Time comes and goes :-) actually, I though I had but it seems I hadn't. No bad.

Merged.

**Pull request merged**
